# Generated by Django 2.1.1 on 2020-09-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200904_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='area',
            new_name='state',
        ),
    ]
