# Generated by Django 2.1.1 on 2020-09-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200905_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='state',
            new_name='area',
        ),
    ]
